### ISSUE TITLE
The latest version of Flutter sdk depends on collection 1.18.0, but http_interop >=2.0.0 depends on collection ^1.19.0

### ISSUE THREAD

**Issue by solody** [f3ath/dart-http-interop#18]
http_interop >=2.0.0 can not be used in flutter project.

Because every version of flutter_test from sdk depends on collection 1.18.0 and http_interop >=2.0.0 depends on collection ^1.19.0

**Comment by solody** [comment]
Is it possible to fix http_interop >=2.0.0 to depends on collection ^1.18.0 ?

**Comment by solody** [comment]
I've upgraded my flutter to v3.25.0-pre, problem resolved.

**Comment by solody** [comment]
Dependding on collection ^1.19.0 make too many conflict with the others, because most developer still using flutter 3.24, and 3.25 is still a pre-release version which bring collection 1.19.0.
Is is possible to change the dependency of collection to ^1.18.0 instead of ^1.19.0?

**Comment by solody** [comment]
I made a pull request here [https://github.com/f3ath/dart-http-interop/pull/19](https://github.com/f3ath/dart-http-interop/pull/19)

**Comment by f3ath** [comment]
LGTM. Thanks.
